/**
 * @file Defines all types of actions that modify games.
 */

// CLIENT TO SERVER
exports.SERVER = {};
exports.SERVER.ADD_WORD = 'ADD_WORD';
exports.SERVER.JOIN_GAME = 'JOIN_GAME';
exports.SERVER.SKIP_WORD = 'SKIP_WORD';
exports.SERVER.CORRECT_WORD = 'CORRECT_WORD';
exports.SERVER.START_GAME = 'START_GAME';
exports.SERVER.START_ROUND = 'START_ROUND';
exports.SERVER.END_ROUND = 'END_ROUND';

// SERVER TO CLIENT
exports.CLIENT = {};

// misc
exports.CLIENT.REPLACE_GAME = 'REPLACE_GAME';

// pre game
exports.CLIENT.PLAYER_JOINED = 'PLAYER_JOINED';
exports.CLIENT.WORD_ADDED = 'WORD_ADDED';
exports.CLIENT.GAME_STARTED = 'GAME_STARTED';

// mid game
exports.CLIENT.ROUND_STARTED = 'ROUND_STARTED';
exports.CLIENT.ROUND_ENDED = 'ROUND_ENDED';
exports.CLIENT.WORD_CORRECT = 'WORD_CORRECT';
exports.CLIENT.WORD_SKIPPED = 'WORD_SKIPPED';


// TODO: Pausing?