/**
 * @file Defines all types of actions that modify games.
 */

// CLIENT TO SERVER
exports.SERVER = {};
exports.SERVER.ADD_WORD = 'ADD_WORD';
exports.SERVER.JOIN_GAME = 'JOIN_GAME';
exports.SERVER.JOIN_GAME = 'SKIP_WORD';
exports.SERVER.JOIN_GAME = 'GUESS_WORD';

// SERVER TO CLIENT
exports.CLIENT = {};
exports.CLIENT.REPLACE_GAME = 'REPLACE_GAME';
exports.CLIENT.PLAYER_JOINED = 'PLAYER_JOINED';
exports.CLIENT.WORD_ADDED = 'WORD_ADDED';
exports.CLIENT.GAME_STARTED = 'GAME_STARTED';
exports.CLIENT.ROUND_STARTED = 'ROUND_STARTED';
exports.CLIENT.ROUND_ENDED = 'ROUND_ENDED';

exports.CLIENT.CORRECT_WORD = 'WORD_GUESSED';
exports.CLIENT.WORD_SKIPPED = 'WORD_SKIPPED';